server:
  port: 8082

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true   #开启请求方式前缀
      datasource:    #配置sentinel持久化中配置文件拉取的数据库信息
        lbkjds: #配置文件的数据源名称（随意命名）
          nacos:
            server-addr: localhost:8848
            data-id: degrade.json
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: degrade  #降级


feign:
  sentinel:
    enabled: true    #开启feign对sentinel的支持

#spring:
#  #application:
#    #name: lbkj-cart-service
#    #name: LBKJ-CART-SERVICE
#
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3307/lbkj_cart_service?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: lengbing_mysql
#    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis-plus:
#  configuration:
#    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
#  global-config:
#    db-config:
#      update-strategy: not_null
#      id-type: auto
#logging:
#  level:
#    com.lengbingkeji: debug
#  pattern:
#    dateformat: HH:mm:ss:SSS
#  file:
#    path: "logs/${spring.application.name}"
#
#knife4j:
#  enable: true
#  openapi:
#    title: lbkj-cart-service接口文档
#    description: "lbkj-cart-service接口文档"
#    email: 1517699467@qq.com
#    concat: 冷冰科技
#    url: http://www.lengbingkeji.com/
#    version: v1.0.0
#    group:
#      default:
#        group-name: default
#        api-rule: package
#        api-rule-resources:
#          - com.lengbingkeji.cart.controller
#
##OpenFeign连接池:okhttp
#feign:
#  okhttp:
#    enabled: true

#动态设置参数
lbkj:
  ds:
    host: localhost
    port: 3307
    database: lbkj_cart_service
    username: root
    password: lengbing_mysql

  swagger:
    title: lbkj-cart-service（购物车）接口文档
    description: lbkj-cart-service（购物车）接口文档
    email: 1517699467@qq.com
    concat: 冷冰科技
    package: com.lengbingkeji.cart.controller

