server:
  port: 8080
spring:
  application:
    #name: lbkj-gateway-service
    name: LBKJ-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: lbkj-item-service # 路由规则id，自定义，唯一
          uri: lb://LBKJ-ITEM-SERVICE # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/items/**,/search/** # 这里是以请求路径作为判断规则
          filters:    #添加路由过滤器：过滤器名=过滤器值
            #- AddRequestHeader=X-Request-Red, Blue-{segment}
            - AddRequestHeader=lengbingkejifilters,lbkjfilters

        - id: lbkj-cart-service
          uri: lb://LBKJ-CART-SERVICE
          predicates:
            - Path=/carts/**

        - id: lbkj-user-service
          uri: lb://LBKJ-USER-SERVICE
          predicates:
            - Path=/users/**,/addresses/**

        - id: lbkj-trade-service
          uri: lb://LBKJ-TRADE-SERVICE
          predicates:
            - Path=/orders/**

        - id: lbkj-pay-service
          uri: lb://LBKJ-PAY-SERVICE
          predicates:
            - Path=/pay-orders/**
      default-filters:
        - AddRequestHeader=lengbingkejifilters-default,lbkjfilters-default

logging:
  level:
    com.lengbingkeji: debug
  pattern:
    dateformat: YYYY-MM-DD HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

#knife4j:
#  enable: true
#  openapi:
#    title: lbkj-gateway-service接口文档
#    description: "lbkj-gateway-service接口文档"
#    email: 1517699467@qq.com
#    concat: 冷冰科技
#    url: http://www.lengbingkeji.com/
#    version: v1.0.0
#    group:
#      default:
#        group-name: default
#        api-rule: package
#        api-rule-resources:
#          - com.lengbingkeji.gateway.controller