server:
  port: 8085
#spring:
#  application:
#    #name: lbkj-pay-service
#    name: LBKJ-PAY-SERVICE
#
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3307/lbkj_pay_service?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: lengbing_mysql
#    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis-plus:
#  configuration:
#    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
#  global-config:
#    db-config:
#      update-strategy: not_null
#      id-type: auto
#logging:
#  level:
#    com.lengbingkeji: debug
#  pattern:
#    dateformat: HH:mm:ss:SSS
#  file:
#    path: "logs/${spring.application.name}"
#
#knife4j:
#  enable: true
#  openapi:
#    title: lbkj-pay-service接口文档
#    description: "lbkj-pay-service接口文档"
#    email: 1517699467@qq.com
#    concat: 冷冰科技
#    url: http://www.lengbingkeji.com/
#    version: v1.0.0
#    group:
#      default:
#        group-name: default
#        api-rule: package
#        api-rule-resources:
#          - com.lengbingkeji.pay.controller
#
##OpenFeign连接池:okhttp
#feign:
#  okhttp:
#    enabled: true
#
##hm:
##  jwt:
##    location: classpath:hmall.jks
##    alias: hmall
##    password: hmall123
##    tokenTTL: 30m
##  auth:
##    excludePaths:
##      - /search/**
##      - /users/login
##      - /items/**
##      - /hi

#动态设置参数
lbkj:
  ds:
    host: localhost
    port: 3307
    database: lbkj_pay_service
    username: root
    password: lengbing_mysql

  swagger:
    title: lbkj-pay-service（支付）接口文档
    description: lbkj-pay-service（支付）接口文档
    email: 1517699467@qq.com
    concat: 冷冰科技
    package: com.lengbingkeji.pay.controller